import React from 'react';
import { PieChart, Pie, Cell, ResponsiveContainer, Tooltip, Legend } from 'recharts';

export const RecommendationPriorityChart = ({ summary }) => {
  if (!summary) return null;

  const data = [
    { name: 'High Priority', value: summary.high || 0, color: '#f43f5e' },
    { name: 'Medium Priority', value: summary.medium || 0, color: '#f59e0b' },
    { name: 'Low Priority', value: summary.low || 0, color: '#3b82f6' },
  ].filter((item) => item.value > 0);

  // Fallback if all 0
  const displayData = data.length > 0 ? data : [{ name: 'No Priority Data', value: 1, color: '#64748b' }];

  return (
    <div className="bg-slate-900/80 border border-slate-800 rounded-2xl p-6 shadow-xl backdrop-blur-sm flex flex-col justify-between">
      <div>
        <h3 className="text-sm font-semibold text-slate-200 uppercase tracking-wider">Recommendation Priority Mix</h3>
        <p className="text-xs text-slate-400">Distribution of action urgency generated by hybrid engine</p>
      </div>

      <div className="h-52 w-full my-2">
        <ResponsiveContainer width="100%" height="100%">
          <PieChart>
            <Pie
              data={displayData}
              cx="50%"
              cy="50%"
              innerRadius={50}
              outerRadius={75}
              paddingAngle={4}
              dataKey="value"
            >
              {displayData.map((entry, index) => (
                <Cell key={`cell-${index}`} fill={entry.color} />
              ))}
            </Pie>
            <Tooltip contentStyle={{ backgroundColor: '#0f172a', borderColor: '#334155', borderRadius: '12px' }} />
            <Legend />
          </PieChart>
        </ResponsiveContainer>
      </div>
    </div>
  );
};

export default RecommendationPriorityChart;
