"""
Feature Engineering Service — IRS Phase 4.

Converts employee/domain objects (from Phase 2 gap analysis and Phase 3
readiness scoring) into a flat, ML-ready feature row.

DISCLAIMER
----------
This module is designed to work with both real employee data (when a live
database is available) and synthetic data generated by DatasetGenerator.
All synthetic data is clearly labelled as academic/demonstration data.

Feature set (28 features)
--------------------------
Employee features:
    experience_years              float   Total years of professional experience
    performance_rating            float   Latest performance rating (1.0–5.0)
    current_grade_encoded         int     Ordinal encoding of current grade (1–5)
    target_grade_encoded          int     Ordinal encoding of target grade (1–5)
    grade_gap                     int     target_encoded − current_encoded (≥1)

Skill features:
    total_skills                  int     Total skills the employee holds
    average_skill_level           float   Mean level across all held skills
    skill_coverage_percentage     float   % of required skills met or exceeded
    mandatory_skill_gap_count     int     Count of mandatory skill gaps
    weighted_skill_gap            float   Sum of (gap × weight) for all skill gaps

Certification features:
    total_certifications          int     Total certifications the employee holds
    completed_certifications      int     Certifications with status=Completed
    certification_completion_rate float   completed / total_required (0.0–1.0)
    mandatory_certification_gap_count int Count of mandatory cert gaps

Project features:
    total_projects                int     Total projects participated in
    completed_projects            int     Alias for total_projects (all are completed)
    lead_projects                 int     Projects where employee was lead
    project_completion_rate       float   total_projects / required_projects (0–1)
    lead_project_completion_rate  float   lead_projects / required_lead (0–1)
    average_project_rating        float   Mean project rating (0.0–5.0)

Readiness score features (from Phase 3):
    skill_score                   float   0.0–40.0
    certification_score           float   0.0–15.0
    experience_score              float   0.0–15.0
    project_score                 float   0.0–20.0
    performance_score             float   0.0–10.0
    readiness_score               float   0.0–100.0

Target:
    promotion_success             int     0 = not promoted, 1 = promoted

DATA LEAKAGE PREVENTION
-----------------------
Only information available at the time of the promotion decision is used.
The following are explicitly excluded:
- Future promotion date
- Future grade after promotion
- Future performance ratings
- Projects completed after the promotion decision
- Certifications completed after the promotion decision
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field

import pandas as pd

from models.employee import Employee
from models.grade_requirement import GradeRequirement

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Grade ordinal encoding — single source of truth
# ---------------------------------------------------------------------------
GRADE_TO_INT: dict[str, int] = {
    "G1": 1, "G2": 2, "G3": 3, "G4": 4, "G5": 5,
}

# ---------------------------------------------------------------------------
# Ordered feature names — used by training AND inference to guarantee
# the feature vector is always in the same column order.
# ---------------------------------------------------------------------------
FEATURE_COLUMNS: list[str] = [
    # Employee
    "experience_years",
    "performance_rating",
    "current_grade_encoded",
    "target_grade_encoded",
    "grade_gap",
    # Skills
    "total_skills",
    "average_skill_level",
    "skill_coverage_percentage",
    "mandatory_skill_gap_count",
    "weighted_skill_gap",
    # Certifications
    "total_certifications",
    "completed_certifications",
    "certification_completion_rate",
    "mandatory_certification_gap_count",
    # Projects
    "total_projects",
    "completed_projects",
    "lead_projects",
    "project_completion_rate",
    "lead_project_completion_rate",
    "average_project_rating",
    # Readiness scores (Phase 3)
    "skill_score",
    "certification_score",
    "experience_score",
    "project_score",
    "performance_score",
    "readiness_score",
]

TARGET_COLUMN: str = "promotion_success"


@dataclass
class FeatureRow:
    """
    A single employee's ML feature row.

    Attributes:
        features:     Ordered dict mapping feature name → value.
        employee_id:  Source employee ID (for traceability).
    """

    features: dict[str, float]
    employee_id: int

    def to_dict(self) -> dict[str, float]:
        """Return features in FEATURE_COLUMNS order."""
        return {col: self.features[col] for col in FEATURE_COLUMNS}

    def to_series(self) -> pd.Series:
        """Return features as a pandas Series in FEATURE_COLUMNS order."""
        return pd.Series(self.to_dict())


class FeatureEngineeringService:
    """
    Converts employee/domain data into ML-ready feature rows.

    This service is the bridge between the rule-based pipeline (Phases 2–3)
    and the ML model (Phase 5).  It is stateless and can be reused across
    multiple employees without re-instantiation.

    Usage
    -----
    >>> svc = FeatureEngineeringService()
    >>> row = svc.build_features(gap_analysis, readiness_result)
    >>> df  = svc.build_dataset(records)   # list of (gap_analysis, result, label)
    """

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def build_features(
        self,
        gap_analysis: dict,
        readiness_result,
    ) -> FeatureRow:
        """
        Build a feature row from Phase 2 + Phase 3 pipeline output.

        Args:
            gap_analysis:     Dict returned by GapAnalysisService.run().
                              Keys: employee, requirement, skill_gaps,
                              certification_gaps, experience_gap, project_gap.
            readiness_result: ReadinessResult returned by ReadinessEngine.calculate().

        Returns:
            FeatureRow with all 26 features populated.
        """
        employee: Employee = gap_analysis["employee"]
        requirement: GradeRequirement = gap_analysis["requirement"]
        skill_gaps: list[dict] = gap_analysis["skill_gaps"]
        cert_gaps: list[dict] = gap_analysis["certification_gaps"]
        proj_gap: dict = gap_analysis["project_gap"]
        bd = readiness_result.breakdown

        features: dict[str, float] = {
            # --- Employee ---
            "experience_years":   float(employee.experience_years),
            "performance_rating": float(employee.performance_rating),
            "current_grade_encoded": float(GRADE_TO_INT.get(employee.current_grade, 0)),
            "target_grade_encoded":  float(GRADE_TO_INT.get(employee.target_grade, 0)),
            "grade_gap": float(
                max(
                    GRADE_TO_INT.get(employee.target_grade, 0)
                    - GRADE_TO_INT.get(employee.current_grade, 0),
                    0,
                )
            ),
            # --- Skills ---
            "total_skills":            float(len(employee.skills)),
            "average_skill_level":     self._avg_skill_level(employee),
            "skill_coverage_percentage": self._skill_coverage_pct(skill_gaps, requirement),
            "mandatory_skill_gap_count": float(
                sum(1 for g in skill_gaps if g.get("mandatory", False))
            ),
            "weighted_skill_gap": self._weighted_skill_gap(skill_gaps, requirement),
            # --- Certifications ---
            "total_certifications": float(len(employee.certifications)),
            "completed_certifications": float(
                sum(1 for c in employee.certifications if c.status.lower() == "completed")
            ),
            "certification_completion_rate": self._cert_completion_rate(
                cert_gaps, requirement
            ),
            "mandatory_certification_gap_count": float(
                sum(1 for g in cert_gaps if g.get("mandatory", False))
            ),
            # --- Projects ---
            "total_projects":    float(len(employee.projects)),
            "completed_projects": float(len(employee.projects)),   # all listed are completed
            "lead_projects":     float(sum(1 for p in employee.projects if p.lead_project)),
            "project_completion_rate":      self._project_completion_rate(proj_gap),
            "lead_project_completion_rate": self._lead_completion_rate(proj_gap),
            "average_project_rating":       self._avg_project_rating(employee),
            # --- Phase 3 readiness scores ---
            "skill_score":         float(bd.skills.score),
            "certification_score": float(bd.certifications.score),
            "experience_score":    float(bd.experience.score),
            "project_score":       float(bd.projects.score),
            "performance_score":   float(bd.performance.score),
            "readiness_score":     float(readiness_result.readiness_score),
        }

        logger.debug(
            "Features built for employee %s: readiness_score=%.2f",
            employee.employee_id,
            features["readiness_score"],
        )
        return FeatureRow(features=features, employee_id=employee.employee_id)

    def validate_features(self, row: FeatureRow) -> list[str]:
        """
        Validate a feature row and return a list of validation errors.

        Args:
            row: The FeatureRow to validate.

        Returns:
            List of error strings.  Empty list means the row is valid.
        """
        errors: list[str] = []
        f = row.features

        # Check all columns present
        for col in FEATURE_COLUMNS:
            if col not in f:
                errors.append(f"Missing feature: {col}")

        if errors:
            return errors  # no point checking ranges if columns are missing

        # Range checks
        _range_checks = [
            ("experience_years",              0.0,  50.0),
            ("performance_rating",            1.0,   5.0),
            ("current_grade_encoded",         1.0,   5.0),
            ("target_grade_encoded",          1.0,   5.0),
            ("grade_gap",                     1.0,   4.0),
            ("skill_coverage_percentage",     0.0, 100.0),
            ("certification_completion_rate", 0.0,   1.0),
            ("project_completion_rate",       0.0,   1.0),
            ("lead_project_completion_rate",  0.0,   1.0),
            ("readiness_score",               0.0, 100.0),
            ("skill_score",                   0.0,  40.0),
            ("certification_score",           0.0,  15.0),
            ("experience_score",              0.0,  15.0),
            ("project_score",                 0.0,  20.0),
            ("performance_score",             0.0,  10.0),
        ]
        for col, lo, hi in _range_checks:
            val = f[col]
            if not (lo <= val <= hi):
                errors.append(f"{col}={val} out of range [{lo}, {hi}]")

        return errors

    def build_dataset(
        self,
        records: list[tuple[dict, object, int]],
    ) -> pd.DataFrame:
        """
        Build a labelled feature DataFrame from a list of records.

        Args:
            records: List of (gap_analysis, readiness_result, promotion_success)
                     tuples.  promotion_success must be 0 or 1.

        Returns:
            DataFrame with FEATURE_COLUMNS + TARGET_COLUMN.
        """
        rows: list[dict] = []
        for gap_analysis, readiness_result, label in records:
            row = self.build_features(gap_analysis, readiness_result)
            d = row.to_dict()
            d[TARGET_COLUMN] = int(label)
            rows.append(d)

        df = pd.DataFrame(rows, columns=FEATURE_COLUMNS + [TARGET_COLUMN])
        logger.info("build_dataset: %d rows, %d features.", len(df), len(FEATURE_COLUMNS))
        return df

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _avg_skill_level(employee: Employee) -> float:
        """
        average_skill_level = sum(skill_level) / total_skills

        Returns 0.0 if the employee has no skills.
        """
        if not employee.skills:
            return 0.0
        return round(
            sum(s.skill_level for s in employee.skills) / len(employee.skills), 2
        )

    @staticmethod
    def _skill_coverage_pct(
        skill_gaps: list[dict],
        requirement: GradeRequirement,
    ) -> float:
        """
        skill_coverage_percentage =
            (required skills where employee meets requirement / total required skills) × 100

        Returns 100.0 if the grade has no skill requirements.
        """
        total = len(requirement.skills)
        if total == 0:
            return 100.0
        gap_names = {g["skill"].lower() for g in skill_gaps}
        met = sum(
            1 for s in requirement.skills
            if s.skill_name.lower() not in gap_names
        )
        return round((met / total) * 100.0, 2)

    @staticmethod
    def _weighted_skill_gap(
        skill_gaps: list[dict],
        requirement: GradeRequirement,
    ) -> float:
        """
        weighted_skill_gap = sum(gap_levels × weight) for each skill gap.

        Uses the weight from the GradeSkillRequirement.  If a skill is
        entirely missing, gap_levels = required_level.
        Returns 0.0 if there are no gaps.
        """
        if not skill_gaps:
            return 0.0
        req_map = {r.skill_name.lower(): r.weight for r in requirement.skills}
        total = 0.0
        for g in skill_gaps:
            weight = req_map.get(g["skill"].lower(), 1.0)
            total += g["gap"] * weight
        return round(total, 4)

    @staticmethod
    def _cert_completion_rate(
        cert_gaps: list[dict],
        requirement: GradeRequirement,
    ) -> float:
        """
        certification_completion_rate =
            completed required certifications / total required certifications

        Returns 1.0 if the grade has no certification requirements.
        """
        total = len(requirement.certifications)
        if total == 0:
            return 1.0
        missing = len(cert_gaps)
        return round((total - missing) / total, 3)

    @staticmethod
    def _project_completion_rate(proj_gap: dict) -> float:
        """
        project_completion_rate = employee_projects / required_projects

        Capped at 1.0.  Returns 1.0 if no projects are required.
        """
        required = proj_gap["required_projects"]
        if required == 0:
            return 1.0
        return round(min(proj_gap["total_projects"] / required, 1.0), 3)

    @staticmethod
    def _lead_completion_rate(proj_gap: dict) -> float:
        """
        lead_project_completion_rate = lead_projects / required_lead_projects

        Capped at 1.0.  Returns 1.0 if no lead projects are required.
        """
        required = proj_gap["required_lead_projects"]
        if required == 0:
            return 1.0
        return round(min(proj_gap["lead_projects"] / required, 1.0), 3)

    @staticmethod
    def _avg_project_rating(employee: Employee) -> float:
        """
        average_project_rating = sum(project_rating) / total_rated_projects

        Returns 0.0 if the employee has no rated projects.
        """
        rated = [
            p.project_rating
            for p in employee.projects
            if p.project_rating is not None
        ]
        if not rated:
            return 0.0
        return round(sum(rated) / len(rated), 2)
