import React, { useState, useEffect } from 'react';
import { getMyRecommendations } from '../api/employeePortalApi';
import { Lightbulb, BookOpen, Award, Briefcase, Users, Star, ArrowRight } from 'lucide-react';

export const EmployeeRecommendationsView = () => {
  const [recs, setRecs] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    getMyRecommendations()
      .then(res => setRecs(res))
      .catch(err => console.error(err))
      .finally(() => setLoading(false));
  }, []);

  if (loading) {
    return <div className="p-8 text-center text-slate-400">Loading recommendations...</div>;
  }

  const learning = recs?.learning || [];
  const certs = recs?.certifications || [];
  const projects = recs?.projects || [];
  const mentorship = recs?.mentorship || [];

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-xl font-bold text-slate-100">Personalized Career Recommendations</h1>
        <p className="text-xs text-slate-400">Prioritized action items generated by the hybrid recommendation engine</p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {/* Learning Paths */}
        <div className="bg-slate-900 border border-slate-800 rounded-3xl p-6 shadow-xl space-y-4">
          <h2 className="text-sm font-bold text-white flex items-center gap-2">
            <BookOpen className="w-4 h-4 text-indigo-400" />
            Learning Paths & Courses
          </h2>
          <div className="space-y-3">
            {learning.map((item, idx) => (
              <div key={idx} className="p-4 bg-slate-950 border border-slate-800 rounded-2xl">
                <div className="flex items-center justify-between">
                  <span className="text-xs font-bold text-slate-200">{item.title || item.course_name}</span>
                  <span className="px-2 py-0.5 bg-indigo-500/20 text-indigo-300 text-[10px] font-bold rounded-md">
                    Priority #{item.priority || idx + 1}
                  </span>
                </div>
                <p className="text-xs text-slate-400 mt-2">{item.description || item.reason}</p>
                <p className="text-[11px] text-indigo-400 mt-2 font-semibold">Duration: {item.estimated_hours || 20} hours</p>
              </div>
            ))}
          </div>
        </div>

        {/* Certifications */}
        <div className="bg-slate-900 border border-slate-800 rounded-3xl p-6 shadow-xl space-y-4">
          <h2 className="text-sm font-bold text-white flex items-center gap-2">
            <Award className="w-4 h-4 text-purple-400" />
            Recommended Certifications
          </h2>
          <div className="space-y-3">
            {certs.map((item, idx) => (
              <div key={idx} className="p-4 bg-slate-950 border border-slate-800 rounded-2xl">
                <span className="text-xs font-bold text-slate-200">{item.title || item.certification_name}</span>
                <p className="text-xs text-slate-400 mt-2">{item.reason || item.description}</p>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
};

export default EmployeeRecommendationsView;
